/** Every tool an agent or MCP client can call through the policy gate. */
export const TOOL_NAMES = [
  "search_recent_tickets",
  "get_incident",
  "get_customer_impact",
  "get_recovery_coverage",
  "get_payment_health",
  "get_recent_deployments",
  "get_service_status",
  "get_infra_health",
  "identify_affected_customers",
  "open_incident",
  "file_engineering_incident",
  "request_rollback_change",
  "open_problem_record",
  "update_engineering_incident",
  "link_ticket_to_incident",
  "add_ticket_note",
  "draft_customer_update",
  "plan_recovery",
  "add_account_note",
  "request_human_approval",
  "send_customer_update",
  "record_contact_preference",
  "issue_recovery_credit",
  "page_on_call",
  "gather_fix_context",
  "start_fix_session",
  "verify_fix",
  "open_fix_pull_request",
  "publish_incident_report",
] as const;

export type ToolName = (typeof TOOL_NAMES)[number];
